---
- include: setup.yml

- name: Set DOCKER_OPTS
  lineinfile: >
    dest=/etc/default/docker regexp=^DOCKER_OPTS=
    line="DOCKER_OPTS=\"{{dokku_docker_opts}}\""
  notify: restart docker

- name: Setup VHOST file
  copy: >
    dest="{{dokku_root}}/VHOST"
    owner=dokku group=dokku mode=0644
    content="{{dokku_vhost | mandatory}}"

- name: Setup dokkurc
  template: >
    src=dokkurc.j2
    dest={{dokku_root}}/dokkurc
    owner=dokku
    mode=0644
    validate='bash -n %s'
  notify: install dokku plugins

- name: Fetch custom dokku plugins
  git: >
    repo="{{ item.repo }}" dest="{{ dokku_plugins_dir }}/{{ item.name }}"
    version="{{ item.version | default('HEAD') }}"
  with_items: dokku_plugins
  notify: install dokku plugins

- name: Set owner and group for installed plugins
  file: >
    dest="{{ dokku_plugins_dir }}/{{ item.name }}"
    recurse=yes owner=root group=root
  with_items: dokku_plugins
  notify: install dokku plugins

# - name: Backport plugin changes
#   copy: >
#     src=plugins/
#     dest={{ dokku_plugins_dir }}
#   notify: install dokku plugins
